Repository commonlispbr/commonlispbr.github.io, pull requests merged in 2018-02, with the labels that each got.

#7 Formatação, restruturação e mais referências
  index.html
  index.org
Labels: WIP, webpage

#12 Adiciona regras simplificada para o grupo
  rules.html
  rules.org
Labels: WIP, discussion

#19 Adiciona Makefile para exportar org => html. Closes #18.
  Makefile
Labels: enhancement, webpage

#24 Remove algumas redundâncias e coloca algumas frases mais claras.
  index.org
Labels: enhancement, webpage
